### ISSUE TITLE
freetype6 should be changed as freetype in building page

### ISSUE THREAD

**Issue by umutuzun** [enginmanap/limonEngine-docs#17]
$ pacman -S freetype6
error: target not found: freetype6

$ pacman -Ss freetype
mingw32/mingw-w64-i686-freetype 2.9.1-1
    TrueType font rendering library (mingw-w64)
mingw64/mingw-w64-x86_64-freetype 2.9.1-1
    TrueType font rendering library (mingw-w64)

**Comment by enginmanap** [comment]
Hi!

Thanks for the contribution. I fixed the issue with commit 330d11 , please note freetype6 is used for historical reason, as shared library version.
